import streamlit as st
import random
import pandas as pd

# --- ページ設定 ---
st.set_page_config(page_title="Life Echo", page_icon="🧬", layout="centered")

# ==========================================
# 🎨 ここが魔法の呪文（デザインCSS）
# ==========================================
st.markdown("""
<style>
    /* 1. アプリ全体の背景をダークに */
    .stApp {
        background-color: #0E1117;
        color: #FAFAFA;
    }
    
    /* 2. ボタンをカッコよくする (グラデーション＆影) */
    div.stButton > button {
        width: 100%;
        background: linear-gradient(90deg, #FF4B4B, #FF914D);
        color: white;
        border: none;
        border-radius: 30px;
        padding: 15px 20px;
        font-weight: bold;
        font-size: 16px;
        box-shadow: 0px 4px 15px rgba(255, 75, 75, 0.4);
        transition: all 0.3s ease;
    }
    div.stButton > button:hover {
        transform: translateY(-2px);
        box-shadow: 0px 8px 20px rgba(255, 75, 75, 0.6);
        color: white;
    }

    /* 3. 数値（Metric）をネオンっぽく光らせる */
    [data-testid="stMetricValue"] {
        font-size: 2.5rem;
        color: #00FFC2;
        text-shadow: 0px 0px 10px rgba(0, 255, 194, 0.5);
    }
    
    /* 4. 上のバーやフッターを消す */
    header {visibility: hidden;}
    footer {visibility: hidden;}
    
    /* 5. タブのデザイン */
    .stTabs [data-baseweb="tab-list"] {
        gap: 10px;
    }
    .stTabs [data-baseweb="tab"] {
        height: 50px;
        white-space: pre-wrap;
        background-color: #1F2530;
        border-radius: 10px;
        color: white;
    }
    .stTabs [aria-selected="true"] {
        background-color: #00FFC2;
        color: black;
    }
</style>
""", unsafe_allow_html=True)

# ==========================================
# ここから下は機能（ロジック）
# ==========================================

st.title("🧬 Life Echo")
st.caption("Music generated by your biometric data.")

# --- タブを作る ---
tab1, tab2 = st.tabs(["🎮 Simulation", "📂 Real Analysis"])

# --- タブ1: 育成ゲーム ---
with tab1:
    st.markdown("### 🧬 Grow your Music")
    
    if 'history' not in st.session_state:
        st.session_state['history'] = []
        st.session_state['history'].append({"day": 0, "tempo": 100, "power": 50})

    last_data = st.session_state['history'][-1]
    
    # データをスタイリッシュに表示
    col1, col2 = st.columns(2)
    with col1:
        st.metric("BPM", last_data['tempo'])
    with col2:
        st.metric("Power", last_data['power'])

    st.write("") # 隙間
    
    if st.button("⚡ Evolve (1 Day Pass)"):
        new_tempo = last_data['tempo'] + random.randint(-10, 10)
        new_power = last_data['power'] + random.randint(-10, 10)
        new_tempo = max(60, min(200, new_tempo))
        new_power = max(0, min(100, new_power))
        
        st.session_state['history'].append({"day": last_data['day']+1, "tempo": new_tempo, "power": new_power})
        st.rerun()

    # グラフ
    st.markdown("#### Growth History")
    chart_data = pd.DataFrame(st.session_state['history'])
    st.line_chart(chart_data, x="day", y=["tempo", "power"], color=["#00FFC2", "#FF4B4B"])


# --- タブ2: リアルデータ分析 ---
with tab2:
    st.markdown("### 📂 Import Life Log")
    
    uploaded_file = st.file_uploader("Upload CSV", type="csv")
    
    if uploaded_file is not None:
        df = pd.read_csv(uploaded_file)
        
        # 最新ログ取得
        latest_log = df.iloc[-1]
        steps = latest_log['steps']
        stress = latest_log['stress']
        
        # ロジック
        music_tempo = int(60 + (steps / 200))
        music_power = int(stress)
        music_tempo = min(180, music_tempo)
        
        # 結果表示エリア
        st.divider()
        st.markdown(f"#### 📅 Date: {latest_log['date']}")
        
        c1, c2, c3 = st.columns(3)
        c1.metric("Steps", steps)
        c2.metric("Target BPM", music_tempo)
        c3.metric("Stress Level", music_power)
        
        # ビジュアル判定
        if music_power > 70:
            mood = "🔥 BURNING"
            audio = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3"
            img = "https://images.unsplash.com/photo-1485470733090-0aae1788d5af?w=600&q=80"
        elif music_tempo < 90:
            mood = "💧 CHILL"
            audio = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3"
            img = "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=600&q=80"
        else:
            mood = "🌿 NORMAL"
            audio = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
            img = "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80"
            
        st.image(img, use_container_width=True)
        st.markdown(f"**Current Mood:** {mood}")
        
        if st.button("▶ Play Generated Track"):
            st.audio(audio)
            
        st.markdown("#### Trends")
        st.line_chart(df, x="date", y=["steps", "stress"], color=["#00FFC2", "#FF4B4B"])